;
; BIND data file, generated by DNS Charm for 
;
$TTL    604800
;@      IN      RR  ADDR
@       IN      SOA     ns.orangebox.com.       root.orangebox.com. ( 16640992 12h 15m 3w 15m )
        IN     NS       ns.orangebox.com.
ns      IN     A        10.0.10.55
mail    IN     CNAME    gmail.com.