#!/usr/bin/python

from common import (
    sanity_check,
    install_bind,
)


# Does not assume offline environment by default
def install():
    if not sanity_check():
        return 0

    # TODO: Check offline, install fatpack
    install_bind()


if __name__ == '__main__':
    install()
