#!/usr/bin/python

import urllib2

from charmhelpers.core.hookenv import log
from charmhelpers.fetch import (
    apt_update,
    apt_install,
)

from common import (
    sanity_check,
    host_ip,
)

# Does not assume offline environment by default 
# TODO: Make offlineable with cached packages
def install():
    sanity_check()
    install_bind()


if __name__ == '__main__':
    install()