#!/usr/bin/python
import os
import sys
# Add charmhelpers to the system path.
try:
    sys.path.insert(0, os.path.abspath(os.path.join(os.environ['CHARM_DIR'],
                                                    'lib')))
    sys.path.insert(0, os.path.abspath(os.path.join(os.environ['CHARM_DIR'],
                                                    'contrib')))
except:
    sys.path.insert(0, os.path.abspath(os.path.join('..', 'lib')))
    sys.path.insert(0, os.path.abspath(os.path.join('..', 'contrib')))


from bind.provider import BindProvider

from charmhelpers.core.hookenv import (
    config,
    unit_get,
    relation_get,
    relation_set,
    relation_id,
)


class ProgrammableChanged(object):

    def __init__(self):
        self.config = config()
        relid = relation_id()
        relation_set(relid, {'public-address': unit_get('public-address')})
        self.add_resource()

    def add_resource(self):
        domain = relation_get('domain')
        resources = relation_get('resources')

        if self.config['provider'] == 'bind':
            bp = BindProvider()
            bp.add_record(resources, domain)


if __name__ == '__main__':
    c = ProgrammableChanged()
