#!/usr/bin/env python
from charmhelpers.core import hookenv
import json
import sys

hooks = hookenv.Hooks()

@hooks.hook('public-website-relation-departed')
def website_departed():
    relid = hookenv.relation_id()

    if not hookenv.relation_get('public-address'):
        log("Relationship incomplete, missing public-address. Exiting")
        return

    # grab an object of the relationship
    reldata = hookenv.relation_for_unit()
    unitkey = reldata['__unit__'].replace('/', '-')

    with open('data/proxy-hosts.json', 'r') as f:
        proxy_hosts = json.loads(f.read())

    proxy_hosts.pop(unitkey, None)

    with open('data/proxy-hosts.json', 'w+') as f:
        f.write(json.dumps(proxy_hosts))

    # TODO: trigger the re-evaluation of the json parsing, and transmission
    # of DNS data back to the upstream DNS provider.


if __name__ == '__main__':
  hooks.execute(sys.argv)
